//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Final_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHistory
    {
        public int ISBN { get; set; }
        public string Account { get; set; }
        public System.DateTime DateBorrow { get; set; }
        public string BookName { get; set; }
        public Nullable<System.DateTime> DateReturn { get; set; }
        public bool IsReturned { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
